name: PR Discord Notify

on:
  pull_request:
    types: [opened, reopened]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_REVIEWERS: ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"🔔 New PR by ${GITHUB_ACTOR}: ${PR_TITLE}\n${PR_URL}\n🔍 Reviewer(s): ${PR_REVIEWERS}\"}" \
            $DISCORD_WEBHOOK
